import { StyleSheet, Platform } from "react-native";

export const C = {
  background:    "#f4f5f7", // screen background
  card:          "#ffffff", // card background
  surface:       "#f7f8fa", // header / section background
  border:        "#e9ecef",
  borderFocus:   "#dfe3e8",
  primary:       "#2c3e50", // dark navy for primary buttons/accents
  textPrimary:   "#000000",
  textSecondary: "#333333",
  textMuted:     "#555555",
  blue:          "#3498db",
  green:         "#2b7a4b",
  red:           "#9e3a3a",
  purple:        "#6f42c1",
  link:          "#2471a3",
};

export const F = {
  bebas:   Platform.OS === "ios" ? "Bebas Neue" : "bebas-neue",
  dm:      Platform.OS === "ios" ? "DM Sans" : "dm-sans",
  mono:    Platform.OS === "ios" ? "Space Mono" : "space-mono",
};

export const tabStyles = StyleSheet.create({
  container: {
    flexDirection: "row",
    backgroundColor: C.surface,
    borderTopWidth: 1,
    borderTopColor: C.border,
    paddingBottom: Platform.OS === "ios" ? 24 : 10,
    paddingTop: 10,
    paddingHorizontal: 6,
    justifyContent: "space-around",
  },
  tab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    position: "relative",
  },
  iconWrap: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  icon: {
    fontSize: 22,
    color: "#888888",
  },
  iconActive: {
    color: C.blue,
  },
  label: {
    fontSize: 10,
    color: "#888888",
    fontWeight: "500",
  },
  labelActive: {
    color: C.blue,
    fontWeight: "700",
  },
  activeDot: {
    position: "absolute",
    bottom: -10,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.blue,
  },
  badge: {
    position: "absolute",
    top: -4,
    right: -8,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: C.red,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: C.surface,
  },
  badgeText: {
    color: "#ffffff",
    fontSize: 9,
    fontWeight: "800",
  },
});

export const headerStyles = StyleSheet.create({
  safe: {
    backgroundColor: C.surface,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  container: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  hamburger: {
    gap: 5,
    alignItems: "flex-start",
  },
  hamburgerLine: {
    width: 20,
    height: 2,
    backgroundColor: C.textPrimary,
    borderRadius: 2,
  },
  title: {
    fontSize: 17,
    fontWeight: "700",
    color: C.textPrimary,
    fontFamily: F.bebas,
    letterSpacing: 1,
  },
  avatarBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#e8f0f5",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#b0cfe0",
  },
  avatarText: {
    color: C.blue,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bebas,
  },
});

export const drawerStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.card },
  profileSection: {
    backgroundColor: C.surface,
    alignItems: "center",
    paddingVertical: 28,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  profileAvatar: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#e8f0f5",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderWidth: 2,
    borderColor: "#b0cfe0",
  },
  profileAvatarText: {
    color: C.blue,
    fontSize: 24,
    fontWeight: "800",
    fontFamily: F.bebas,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "700",
    color: C.textPrimary,
  },
  profileUnit: {
    fontSize: 13,
    color: C.textMuted,
    marginBottom: 12,
    fontFamily: F.mono,
  },
  scoreChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1.5,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderColor: C.border,
  },
  scoreDot: { width: 7, height: 7, borderRadius: 4 },
  scoreChipText: { fontSize: 12, fontWeight: "700", color: C.textMuted },
  navScroll: { flex: 1, paddingHorizontal: 12, paddingTop: 16 },
  navGroupLabel: {
    fontSize: 11, fontWeight: "700", color: "#888888",
    textTransform: "uppercase", letterSpacing: 1.5,
    paddingHorizontal: 8, marginBottom: 6, marginTop: 4,
    fontFamily: F.mono,
  },
  navItem: {
    flexDirection: "row", alignItems: "center",
    gap: 14, paddingVertical: 13, paddingHorizontal: 12,
    borderRadius: 4, marginBottom: 2,
  },
  navIconContainer: { width: 26, alignItems: "center", justifyContent: "center" },
  navLabel: { flex: 1, fontSize: 15, fontWeight: "600", color: C.textSecondary },
  navBadge: {
    width: 20, height: 20, borderRadius: 10,
    backgroundColor: C.red,
    alignItems: "center", justifyContent: "center",
  },
  navBadgeText: { color: "#ffffff", fontSize: 11, fontWeight: "700" },
  divider: { height: 1, backgroundColor: C.border, marginVertical: 12 },
  logoutSection: {
    borderTopWidth: 1, borderTopColor: C.border,
    paddingHorizontal: 20, paddingVertical: 16,
    backgroundColor: C.surface,
  },
  logoutBtn: {
    flexDirection: "row", alignItems: "center", gap: 12,
    paddingVertical: 12, paddingHorizontal: 12,
    backgroundColor: "#fbeaea",
    borderRadius: 4, borderWidth: 1, borderColor: "#e5bdbd",
    marginBottom: 12,
  },
  logoutIcon: { fontSize: 18 },
  logoutText: { fontSize: 15, fontWeight: "700", color: C.red },
  version: { fontSize: 11, color: "#888888", textAlign: "center" },
});

export const sharedStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.background },
  container: { padding: 16 },
  card: {
    backgroundColor: C.card,
    borderRadius: 6,
    padding: 16,
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: C.textPrimary,
    fontFamily: F.bebas,
    letterSpacing: 1,
    marginBottom: 12,
  },
  input: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 3,
    padding: 14,
    fontSize: 15,
    color: C.textPrimary,
    fontFamily: F.dm,
  },
  btnPrimary: {
    backgroundColor: C.primary,
    borderRadius: 3,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  btnPrimaryText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
    fontFamily: F.dm,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  btnGhost: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 3,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  btnGhostText: {
    color: C.textSecondary,
    fontSize: 15,
    fontWeight: "500",
    fontFamily: F.dm,
    letterSpacing: 0.5,
  },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 3,
    borderWidth: 1,
  },
  pillText: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    fontFamily: F.mono,
    letterSpacing: 1,
  },
  emptyText: {
    fontSize: 14,
    color: "#888888",
    textAlign: "center",
    paddingVertical: 24,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: C.background,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    color: C.textMuted,
    marginTop: 12,
    fontSize: 14,
    fontFamily: F.mono,
  },
});