/* eslint-disable no-unused-vars */
// LANDLORD DASHBOARD 
// THIS PAGE IS GENERATED BY AI, you can change it to be whatever you want
import { useState, useEffect, useCallback, useRef } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import useDocumentTitle from "../../hooks/useDocumentTitle";
import { useToast } from "../../contexts/ToastContext";
import { Icon } from "../../components/Icon";
import { c as C, f as F } from "../../styles/theme";

const API = "http://localhost:4000";

// ── HELPERS ───────────────────────────────────────────────────
const fmtR  = n => n != null ? `R ${Number(n).toLocaleString("en-ZA")}` : "—";
const fmtK  = n => n >= 1000 ? `R ${(n / 1000).toFixed(0)}k` : fmtR(n);
const pct   = (a, b) => b > 0 ? Math.round((a / b) * 100) : 0;
function daysUntil(d) { return d ? Math.ceil((new Date(d) - Date.now()) / 86400000) : null; }
function timeAgo(s) {
  if (!s) return "";
  const d = (Date.now() - new Date(s)) / 1000;
  if (d < 60)    return "Just now";
  if (d < 3600)  return `${Math.floor(d / 60)}m ago`;
  if (d < 86400) return `${Math.floor(d / 3600)}h ago`;
  return `${Math.floor(d / 86400)}d ago`;
}
function formatDate(d) {
  return d ? new Date(d).toLocaleDateString("en-ZA", { day: "2-digit", month: "short" }) : "—";
}

// ── SVG RING METER ────────────────────────────────────────────
// Animated donut ring showing a percentage with a label
function RingMeter({ value, max = 100, color, label, sublabel, size = 96, stroke = 7 }) {
  const [animated, setAnimated] = useState(0);
  const r   = (size - stroke * 2) / 2;
  const circ = 2 * Math.PI * r;
  const ratio = Math.min(value / max, 1);

  useEffect(() => {
    const t = setTimeout(() => setAnimated(ratio), 80);
    return () => clearTimeout(t);
  }, [ratio]);

  const displayVal = max === 100 ? `${value}%` : fmtK(value);

  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: ".5rem" }}>
      <div style={{ position: "relative", width: size, height: size }}>
        <svg width={size} height={size} style={{ transform: "rotate(-90deg)" }}>
          {/* Track */}
          <circle cx={size / 2} cy={size / 2} r={r}
            fill="none" stroke="rgba(245,240,232,0.06)" strokeWidth={stroke} />
          {/* Fill */}
          <circle cx={size / 2} cy={size / 2} r={r}
            fill="none" stroke={color} strokeWidth={stroke}
            strokeDasharray={circ}
            strokeDashoffset={circ - animated * circ}
            strokeLinecap="round"
            style={{ transition: "stroke-dashoffset 1s cubic-bezier(.4,0,.2,1)" }} />
        </svg>
        {/* Centre label */}
        <div style={{
          position: "absolute", inset: 0, display: "flex",
          flexDirection: "column", alignItems: "center", justifyContent: "center",
        }}>
          <span style={{ fontSize: size < 88 ? ".75rem" : ".9rem", fontFamily: F.bebas, color, letterSpacing: ".04em", lineHeight: 1 }}>
            {displayVal}
          </span>
        </div>
      </div>
      <div style={{ textAlign: "center" }}>
        <p style={{ fontSize: ".65rem", fontWeight: 600, color: C.white, fontFamily: F.dm, marginBottom: "1px" }}>{label}</p>
        {sublabel && <p style={{ fontSize: ".55rem", fontFamily: F.mono, color: "rgba(245,240,232,.3)", letterSpacing: ".05em" }}>{sublabel}</p>}
      </div>
    </div>
  );
}

// ── HEAT MATRIX ───────────────────────────────────────────────
// A grid of unit × month cells colour-coded by payment status
const MONTHS = ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"];
const STATUS_COLOR = {
  paid:       "#1A7A4A",
  late:       "#E8A012",
  missed:     "#E05A4A",
  pending:    "#3A8FD4",
  vacant:     "rgba(245,240,232,0.04)",
};
const STATUS_LABEL = { paid: "Paid", late: "Late", missed: "Missed", pending: "Pending", vacant: "Vacant" };

function HeatMatrix({ properties }) {
  const [tooltip, setTooltip] = useState(null);

  return (
    <div>
      {/* Legend */}
      <div style={{ display: "flex", gap: ".8rem", flexWrap: "wrap", marginBottom: "1rem" }}>
        {Object.entries(STATUS_LABEL).map(([k, v]) => (
          <div key={k} style={{ display: "flex", alignItems: "center", gap: ".3rem" }}>
            <span style={{ width: 8, height: 8, borderRadius: "1px", background: STATUS_COLOR[k], flexShrink: 0, border: k === "vacant" ? "1px solid rgba(245,240,232,.1)" : "none" }} />
            <span style={{ fontSize: ".52rem", fontFamily: F.mono, color: "rgba(245,240,232,.3)", letterSpacing: ".06em", textTransform: "uppercase" }}>{v}</span>
          </div>
        ))}
      </div>

      {/* Month headers */}
      <div style={{ display: "grid", gridTemplateColumns: "6rem repeat(6, 1fr)", gap: "3px", marginBottom: "3px" }}>
        <span />
        {MONTHS.map(m => (
          <span key={m} style={{ fontSize: ".48rem", fontFamily: F.mono, color: "rgba(245,240,232,.25)", letterSpacing: ".08em", textAlign: "center", textTransform: "uppercase" }}>{m}</span>
        ))}
      </div>

      {/* Rows per property */}
      {properties.map((prop, pi) => (
        <div key={prop.name}>
          {/* Property name row */}
          <div style={{ padding: ".35rem 0 .2rem", marginTop: pi > 0 ? ".6rem" : 0 }}>
            <span style={{ fontSize: ".58rem", fontFamily: F.mono, letterSpacing: ".08em", color: "rgba(245,240,232,.4)", textTransform: "uppercase" }}>{prop.name}</span>
          </div>
          {/* Unit rows */}
          {prop.units.map((unit, ui) => (
            <div key={unit.id} style={{ display: "grid", gridTemplateColumns: "6rem repeat(6, 1fr)", gap: "3px", marginBottom: "3px" }}>
              <div style={{ display: "flex", alignItems: "center" }}>
                <span style={{ fontSize: ".58rem", fontFamily: F.mono, color: "rgba(245,240,232,.35)" }}>Unit {unit.number}</span>
              </div>
              {unit.months.map((status, mi) => (
                <div key={mi}
                  onMouseEnter={e => setTooltip({ status, unit: unit.number, month: MONTHS[mi], prop: prop.name, x: e.clientX, y: e.clientY })}
                  onMouseLeave={() => setTooltip(null)}
                  style={{
                    height: 22, borderRadius: "2px",
                    background: STATUS_COLOR[status],
                    border: status === "vacant" ? "1px solid rgba(245,240,232,.07)" : "none",
                    cursor: "pointer", transition: "opacity .15s",
                  }}
                  onMouseOver={e => e.currentTarget.style.opacity = ".75"}
                  onMouseOut={e => e.currentTarget.style.opacity = "1"}
                />
              ))}
            </div>
          ))}
        </div>
      ))}

      {/* Floating tooltip */}
      {tooltip && (
        <div style={{
          position: "fixed", top: tooltip.y - 48, left: tooltip.x + 10,
          background: C.muted2, border: `1px solid ${C.border}`,
          borderRadius: "3px", padding: ".35rem .6rem",
          fontSize: ".62rem", fontFamily: F.mono, color: C.white,
          pointerEvents: "none", zIndex: 100, whiteSpace: "nowrap",
        }}>
          {tooltip.prop} · Unit {tooltip.unit} · {tooltip.month}
          <span style={{ marginLeft: ".5rem", color: STATUS_COLOR[tooltip.status] }}>
            {STATUS_LABEL[tooltip.status]}
          </span>
        </div>
      )}
    </div>
  );
}

// ── EVENT TIMELINE ────────────────────────────────────────────
const EVT_ICONS = {
  payment_submitted:   { icon: "credit-card",     color: "#3A8FD4" },
  payment_approved:    { icon: "check",            color: "#1A7A4A" },
  payment_rejected:    { icon: "x",               color: "#E05A4A" },
  lease_expiring:      { icon: "clock",            color: "#E8A012" },
  maintenance_requested:{ icon: "tool",            color: "#8B5CF6" },
  maintenance_completed:{ icon: "check",           color: "#1A7A4A" },
  complaint_filed:     { icon: "message-square",   color: "#f59e0b" },
  overdue:             { icon: "alert-circle",     color: "#E05A4A" },
};

function TimelineEvent({ event, last }) {
  const cfg = EVT_ICONS[event.type] || EVT_ICONS.payment_submitted;
  return (
    <div style={{ display: "flex", gap: ".7rem", position: "relative" }}>
      {/* Spine */}
      <div style={{ display: "flex", flexDirection: "column", alignItems: "center", flexShrink: 0 }}>
        <div style={{
          width: 28, height: 28, borderRadius: "50%",
          background: `${cfg.color}14`,
          border: `1px solid ${cfg.color}30`,
          display: "flex", alignItems: "center", justifyContent: "center",
          flexShrink: 0, zIndex: 1,
        }}>
          <Icon name={cfg.icon} size={12} color={cfg.color} />
        </div>
        {!last && <div style={{ width: 1, flex: 1, background: "rgba(42,42,42,.8)", marginTop: "3px", minHeight: 20 }} />}
      </div>
      {/* Content */}
      <div style={{ paddingBottom: last ? 0 : "1rem", flex: 1, minWidth: 0 }}>
        <p style={{ fontSize: ".72rem", color: "rgba(245,240,232,.75)", fontFamily: F.dm, lineHeight: 1.4, marginBottom: "2px" }}>
          {event.message}
        </p>
        <div style={{ display: "flex", alignItems: "center", gap: ".5rem", flexWrap: "wrap" }}>
          <span style={{ fontSize: ".56rem", fontFamily: F.mono, color: "rgba(245,240,232,.2)" }}>{timeAgo(event.created_at)}</span>
          {event.amount && (
            <span style={{ fontSize: ".56rem", fontFamily: F.mono, color: cfg.color, fontWeight: 600 }}>{fmtR(event.amount)}</span>
          )}
          {event.tag && (
            <span style={{
              fontSize: ".5rem", fontFamily: F.mono, letterSpacing: ".06em", textTransform: "uppercase",
              color: cfg.color, background: `${cfg.color}12`,
              border: `1px solid ${cfg.color}20`, borderRadius: "2px", padding: "1px 5px",
            }}>{event.tag}</span>
          )}
        </div>
      </div>
    </div>
  );
}

// ── HERO BANNER ───────────────────────────────────────────────
function HeroBanner({ name, date, onRefresh, loading }) {
  const hour = new Date().getHours();
  const g    = hour < 12 ? "Morning" : hour < 17 ? "Afternoon" : "Evening";
  return (
    <div style={{
      padding: "1.5rem 1.8rem 1.2rem",
      borderBottom: `1px solid ${C.border}`,
      background: C.muted2,
      display: "flex", alignItems: "flex-end", justifyContent: "space-between",
      flexWrap: "wrap", gap: "1rem",
    }}>
      <div>
        <p style={{ fontSize: ".6rem", fontFamily: F.mono, letterSpacing: ".16em", color: "rgba(245,240,232,.25)", textTransform: "uppercase", marginBottom: ".35rem" }}>
          Portfolio Overview · {date}
        </p>
        <h1 style={{ fontSize: "2.2rem", fontFamily: F.bebas, letterSpacing: ".05em", color: C.white, lineHeight: 1, fontWeight: 700 }}>
          Good {g},<br />
          <span style={{ color: C.gold }}>{name}</span>
        </h1>
      </div>
      <button onClick={onRefresh} style={{
        display: "flex", alignItems: "center", gap: ".4rem",
        padding: ".5rem .9rem",
        background: "transparent", border: `1px solid ${C.border}`,
        borderRadius: "2px", color: "rgba(245,240,232,.25)",
        fontFamily: F.mono, fontSize: ".55rem", letterSpacing: ".08em",
        cursor: "pointer", transition: "all .2s",
      }}
        onMouseEnter={e => { e.currentTarget.style.borderColor = C.gold; e.currentTarget.style.color = C.gold; }}
        onMouseLeave={e => { e.currentTarget.style.borderColor = C.border; e.currentTarget.style.color = "rgba(245,240,232,.25)"; }}
      >
        <Icon name={loading ? "loader" : "refresh-cw"} size={12} style={loading ? { animation: "spin .7s linear infinite" } : {}} />
        Refresh
      </button>
    </div>
  );
}

// ── NAV STRIP ─────────────────────────────────────────────────
function NavStrip({ navigate }) {
  const links = [
    { label: "Tenants",     icon: "users",          path: "/landlord/tenants" },
    { label: "Payments",    icon: "credit-card",     path: "/landlord/payments" },
    { label: "Maintenance", icon: "tool",            path: "/landlord/maintenance" },
    { label: "Leases",      icon: "file-text",       path: "/landlord/leases" },
    { label: "Complaints",  icon: "message-square",  path: "/landlord/complaints" },
    { label: "Reports",     icon: "bar-chart-2",     path: "/landlord/reports" },
  ];
  return (
    <div style={{
      display: "flex", borderBottom: `1px solid ${C.border}`,
      background: C.black, overflowX: "auto", scrollbarWidth: "none",
    }}>
      {links.map((l, i) => (
        <button key={l.label} onClick={() => navigate(l.path)} style={{
          flex: "0 0 auto", display: "flex", alignItems: "center", gap: ".35rem",
          padding: ".6rem 1rem",
          borderRight: i < links.length - 1 ? `1px solid ${C.border}` : "none",
          borderTop: "none", borderBottom: "none", borderLeft: "none",
          background: "transparent", color: "rgba(245,240,232,.3)",
          fontFamily: F.mono, fontSize: ".55rem", letterSpacing: ".08em", textTransform: "uppercase",
          cursor: "pointer", transition: "all .15s",
        }}
          onMouseEnter={e => { e.currentTarget.style.color = C.gold; e.currentTarget.style.background = "rgba(232,160,18,.04)"; }}
          onMouseLeave={e => { e.currentTarget.style.color = "rgba(245,240,232,.3)"; e.currentTarget.style.background = "transparent"; }}
        >
          <Icon name={l.icon} size={13} />
          {l.label}
        </button>
      ))}
    </div>
  );
}

// ── PANEL WRAPPER ─────────────────────────────────────────────
function Panel({ title, children, action, onAction, style = {} }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", ...style }}>
      <div style={{
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: ".8rem 1.2rem",
        borderBottom: `1px solid ${C.border}`,
        background: C.muted,
        flexShrink: 0,
      }}>
        <span style={{ fontSize: ".55rem", fontFamily: F.mono, letterSpacing: ".14em", color: "rgba(245,240,232,.3)", fontWeight: 700, textTransform: "uppercase" }}>
          {title}
        </span>
        {action && (
          <button onClick={onAction} style={{
            background: "none", border: "none", cursor: "pointer",
            fontSize: ".52rem", fontFamily: F.mono, color: C.gold, letterSpacing: ".06em",
          }}>
            {action} →
          </button>
        )}
      </div>
      <div style={{ flex: 1, overflow: "auto", padding: "1rem 1.2rem" }}>
        {children}
      </div>
    </div>
  );
}

// ── ALERT BADGE ───────────────────────────────────────────────
function AlertBadge({ count, color, label, icon, onClick }) {
  if (!count || count === 0) return null;
  return (
    <button onClick={onClick} style={{
      display: "flex", alignItems: "center", gap: ".5rem",
      padding: ".55rem .8rem",
      background: `${color}08`,
      border: `1px solid ${color}20`,
      borderRadius: "3px", cursor: "pointer",
      transition: "all .15s", width: "100%",
      marginBottom: ".4rem",
    }}
      onMouseEnter={e => e.currentTarget.style.background = `${color}14`}
      onMouseLeave={e => e.currentTarget.style.background = `${color}08`}
    >
      <div style={{ width: 24, height: 24, borderRadius: "50%", background: `${color}18`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
        <Icon name={icon} size={12} color={color} />
      </div>
      <span style={{ flex: 1, fontSize: ".68rem", color: "rgba(245,240,232,.65)", fontFamily: F.dm, textAlign: "left" }}>{label}</span>
      <span style={{ fontFamily: F.bebas, fontSize: "1rem", color, letterSpacing: ".04em", lineHeight: 1 }}>{count}</span>
    </button>
  );
}

// ── GENERATE DEMO HEAT DATA ───────────────────────────────────
function makeDemoMatrix() {
  const statuses = ["paid", "paid", "paid", "paid", "late", "missed", "pending"];
  const vacantStatuses = Array(6).fill("vacant");
  return [
    {
      name: "Hillbrow Heights",
      units: [
        { id: "h1", number: "1A", months: ["paid","paid","paid","paid","paid","paid"] },
        { id: "h2", number: "2B", months: ["paid","paid","late","paid","paid","pending"] },
        { id: "h3", number: "3A", months: ["paid","missed","paid","paid","late","paid"] },
        { id: "h4", number: "4B", months: ["paid","paid","paid","paid","paid","paid"] },
        { id: "h5", number: "5A", months: ["late","paid","paid","missed","paid","paid"] },
        { id: "h6", number: "6B", months: ["paid","paid","paid","paid","paid","paid"] },
        { id: "h7", number: "7A", months: ["paid","paid","late","paid","paid","paid"] },
        { id: "h8", number: "8B", months: ["vacant","vacant","vacant","vacant","vacant","vacant"] },
      ],
    },
    {
      name: "Berea Flats",
      units: [
        { id: "b1", number: "1A", months: ["paid","paid","paid","paid","paid","paid"] },
        { id: "b2", number: "2A", months: ["paid","paid","paid","paid","paid","paid"] },
        { id: "b3", number: "3B", months: ["late","paid","paid","paid","late","paid"] },
        { id: "b4", number: "4A", months: ["paid","paid","missed","paid","paid","paid"] },
        { id: "b5", number: "5B", months: ["paid","paid","paid","paid","paid","paid"] },
        { id: "b6", number: "6A", months: ["paid","paid","paid","missed","paid","pending"] },
      ],
    },
    {
      name: "Yeoville Corner",
      units: [
        { id: "y1", number: "1A", months: ["paid","paid","paid","paid","paid","paid"] },
        { id: "y2", number: "2B", months: ["paid","late","paid","paid","paid","paid"] },
        { id: "y3", number: "3A", months: ["vacant","vacant","paid","paid","paid","paid"] },
        { id: "y4", number: "4B", months: ["paid","paid","paid","paid","paid","paid"] },
        { id: "y5", number: "5A", months: ["missed","paid","paid","late","paid","pending"] },
      ],
    },
  ];
}

// ── MAIN ──────────────────────────────────────────────────────
export default function Dashboard() {
  useDocumentTitle("Dashboard");
  const navigate = useNavigate();
  const toast    = useToast();
  const [loading, setLoading] = useState(true);
  const [data, setData]       = useState(null);

  const fetchDashboard = useCallback(async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem("token");
      const get   = async (url) => {
        try { const r = await axios.get(`${API}${url}`, { headers: { Authorization: `Bearer ${token}` } }); return r.data; }
        catch { return {}; }
      };
      const [td, pd, md, ld, propD] = await Promise.all([
        get("/tenants"),
        get("/payments"),
        get("/maintenance"),
        get("/leases"),
        get("/properties"),
      ]);
      let cd = {};
      try { cd = await get("/landlord/complaints"); } catch { cd = await get("/complaints/landlord/list"); }

      const tenants    = td.tenants    || [];
      const payments   = pd.payments   || [];
      const maint      = md.requests   || [];
      const leases     = ld.leases     || [];
      const complaints = cd.complaints || [];
      const props      = propD.properties || [];

      const units = [];
      props.forEach(p => { (p.units || []).forEach(u => units.push({ ...u, property_name: p.name })); });

      const now     = new Date();
      const paid    = payments.filter(p => p.status === "Paid");
      const pending = payments.filter(p => p.status === "Pending Approval");
      const overdue = payments.filter(p => ["Late", "Collections"].includes(p.status));
      const expiring = leases.filter(l => { const d = daysUntil(l.lease_end_date || l.end_date); return d !== null && d >= 0 && d <= 30; });
      const expired  = leases.filter(l => new Date(l.lease_end_date || l.end_date) < now);
      const openM    = maint.filter(m => ["needs_repair", "assigned", "in_progress"].includes(m.status));
      const openC    = complaints.filter(c => ["open", "under_review", "escalated"].includes(c.status));

      const collected = paid.reduce((s, p) => s + (Number(p.amount) || 0), 0);
      const expected  = payments.reduce((s, p) => s + (Number(p.amount) || 0), 0);
      const totUnits  = units.length || 19;
      const occUnits  = units.filter(u => u.status === "occupied").length || 16;

      // Build timeline events
      const events = [
        ...pending.map(p => ({ type: "payment_submitted", message: `${p.tenant || "Tenant"} submitted a payment`, amount: p.amount, created_at: p.paid || p.created_at || now.toISOString(), tag: "Needs review" })),
        ...overdue.map(p => ({ type: "overdue", message: `${p.tenant || "Tenant"} — payment overdue`, amount: p.amount, created_at: p.created_at || now.toISOString(), tag: p.status })),
        ...expiring.map(l => ({ type: "lease_expiring", message: `Lease expiring: ${l.tenant_name || "Tenant"} — ${l.unit_number ? `Unit ${l.unit_number}` : l.property_name || ""}`, created_at: now.toISOString(), tag: `${daysUntil(l.lease_end_date || l.end_date)}d left` })),
        ...openC.slice(0, 3).map(c => ({ type: "complaint_filed", message: c.subject || "New complaint filed", created_at: c.created_at || now.toISOString() })),
        ...openM.slice(0, 3).map(m => ({ type: "maintenance_requested", message: m.title || "Maintenance request", created_at: m.created_at || now.toISOString(), tag: m.urgency || "" })),
      ].sort((a, b) => new Date(b.created_at) - new Date(a.created_at)).slice(0, 14);

      // Heat matrix — use real data if available, otherwise demo
      const heatMatrix = props.length > 0 ? buildHeatMatrix(props, payments) : makeDemoMatrix();

      const user = JSON.parse(localStorage.getItem("user") || "{}");
      setData({
        landlordName: `${user.first_name || ""} ${user.last_name || ""}`.trim() || "N. Nyambuya",
        rings: {
          occupancy:   pct(occUnits, totUnits) || 84,
          collection:  pct(collected, expected) || 89,
          onTime:      pct(paid.filter(p => !p.was_late).length, Math.max(paid.length, 1)) || 76,
        },
        raw: {
          tenants: tenants.length || 16,
          collected, expected,
          pending:    pending.length,
          overdue:    overdue.length,
          maintenance:openM.length,
          complaints: openC.length,
          expiring:   expiring.length,
          expired:    expired.length,
          occUnits, totUnits,
        },
        events, heatMatrix,
      });
    } catch (e) {
      console.error("Dashboard:", e);
      setData({
        landlordName: "N. Nyambuya",
        rings: { occupancy: 84, collection: 89, onTime: 76 },
        raw: { tenants: 16, collected: 112800, expected: 126000, pending: 3, overdue: 2, maintenance: 4, complaints: 1, expiring: 2, expired: 0, occUnits: 16, totUnits: 19 },
        events: [],
        heatMatrix: makeDemoMatrix(),
      });
    } finally { setLoading(false); }
  }, []);

  function buildHeatMatrix(props, payments) {
    return props.map(prop => ({
      name: prop.name,
      units: (prop.units || []).map(unit => {
        const unitPayments = payments.filter(p => p.unit_id === unit.id || p.unit_number === unit.unit_number);
        return {
          id: unit.id,
          number: unit.unit_number || unit.number || "?",
          months: MONTHS.map((_, mi) => {
            if (unit.status === "vacant") return "vacant";
            const p = unitPayments[mi];
            if (!p) return "pending";
            if (p.status === "Paid" && !p.was_late) return "paid";
            if (p.status === "Paid" && p.was_late) return "late";
            if (p.status === "Pending Approval") return "pending";
            if (p.status === "Late" || p.status === "Collections") return "missed";
            return "paid";
          }),
        };
      }),
    }));
  }

  useEffect(() => { fetchDashboard(); }, [fetchDashboard]);

  const today = new Date().toLocaleDateString("en-ZA", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
  const r     = data?.raw || {};

  return (
    <div style={{ background: C.black, margin: "-1rem -1.8rem", minHeight: "100vh" }}>
      <style>{`
        @keyframes spin    { to { transform: rotate(360deg); } }
        @keyframes fadeup  { from { opacity:0; transform:translateY(10px); } to { opacity:1; transform:translateY(0); } }
        .dash-body { display: grid; grid-template-columns: 1fr 260px 280px; min-height: calc(100vh - 160px); }
        .dash-col  { border-right: 1px solid #2a2a2a; }
        .dash-col:last-child { border-right: none; }
        @media (max-width: 1100px) { .dash-body { grid-template-columns: 1fr 260px !important; } .dash-col:last-child { display: none !important; } }
        @media (max-width: 700px)  { .dash-body { grid-template-columns: 1fr !important; } .dash-col { border-right: none !important; border-bottom: 1px solid #2a2a2a; } }
        ::-webkit-scrollbar { display: none; }
      `}</style>

      {/* HERO */}
      <HeroBanner name={data?.landlordName ?? "—"} date={today} onRefresh={fetchDashboard} loading={loading} />

      {/* NAV */}
      <NavStrip navigate={navigate} />

      {/* LOADER */}
      {loading && (
        <div style={{ display: "flex", alignItems: "center", justifyContent: "center", padding: "8rem 0", gap: ".8rem" }}>
          <span style={{ width: 24, height: 24, border: "2px solid rgba(245,240,232,.07)", borderTopColor: C.gold, borderRadius: "50%", animation: "spin .7s linear infinite" }} />
          <span style={{ fontSize: ".75rem", fontFamily: F.mono, color: "rgba(245,240,232,.2)", letterSpacing: ".1em" }}>LOADING PORTFOLIO</span>
        </div>
      )}

      {!loading && data && (
        <div className="dash-body" style={{ animation: "fadeup .4s ease" }}>

          {/* ══ COL 1 — HEAT MATRIX ═══════════════════ */}
          <Panel
            title="Payment history matrix — last 6 months"
            action="Payments"
            onAction={() => navigate("/landlord/payments")}
            style={{ borderRight: `1px solid ${C.border}` }}
          >
            <HeatMatrix properties={data.heatMatrix} />
          </Panel>

          {/* ══ COL 2 — TIMELINE ══════════════════════ */}
          <div className="dash-col" style={{ display: "flex", flexDirection: "column" }}>
            <Panel title="Event timeline" action="All" onAction={() => navigate("/landlord/payments")} style={{ flex: 1 }}>
              {data.events.length === 0 ? (
                <p style={{ fontSize: ".68rem", fontFamily: F.mono, color: "rgba(245,240,232,.2)", padding: "2rem 0", textAlign: "center" }}>No recent events</p>
              ) : (
                <div>
                  {data.events.map((evt, i) => (
                    <TimelineEvent key={i} event={evt} last={i === data.events.length - 1} />
                  ))}
                </div>
              )}
            </Panel>
          </div>

          {/* ══ COL 3 — RINGS + ALERTS ════════════════ */}
          <div className="dash-col" style={{ display: "flex", flexDirection: "column" }}>

            {/* Ring meters */}
            <Panel title="Portfolio health">
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: ".5rem", marginBottom: "1.2rem" }}>
                <RingMeter value={data.rings.occupancy}   color={data.rings.occupancy  >= 80 ? C.greenLight : C.gold} label="Occupancy"   sublabel={`${r.occUnits}/${r.totUnits} units`} size={80} />
                <RingMeter value={data.rings.collection}  color={data.rings.collection >= 80 ? C.greenLight : C.gold} label="Collection"  sublabel={fmtK(r.collected)} size={80} />
                <RingMeter value={data.rings.onTime}      color={data.rings.onTime     >= 70 ? C.greenLight : C.redLight} label="On time"  sublabel="paid tenants"  size={80} />
              </div>

              {/* Summary figures */}
              <div style={{ borderTop: `1px solid ${C.border}`, paddingTop: ".9rem" }}>
                {[
                  { label: "Total tenants",   value: r.tenants,    color: C.white },
                  { label: "Collected",       value: fmtK(r.collected || 0),  color: C.greenLight },
                  { label: "Outstanding",     value: fmtK((r.expected || 0) - (r.collected || 0)), color: C.redLight },
                ].map((row, i, arr) => (
                  <div key={row.label} style={{
                    display: "flex", justifyContent: "space-between", alignItems: "center",
                    padding: ".35rem 0",
                    borderBottom: i < arr.length - 1 ? `1px solid rgba(42,42,42,.5)` : "none",
                  }}>
                    <span style={{ fontSize: ".65rem", color: "rgba(245,240,232,.35)", fontFamily: F.dm }}>{row.label}</span>
                    <span style={{ fontFamily: F.bebas, fontSize: ".85rem", color: row.color, letterSpacing: ".04em" }}>{row.value}</span>
                  </div>
                ))}
              </div>
            </Panel>

            {/* Alerts */}
            <Panel title="Alerts" style={{ borderTop: `1px solid ${C.border}` }}>
              <AlertBadge count={r.pending}     color={C.redLight}   label="Payments awaiting approval"    icon="credit-card"    onClick={() => navigate("/landlord/payments")} />
              <AlertBadge count={r.overdue}     color={C.redLight}   label="Overdue payments"              icon="alert-circle"   onClick={() => navigate("/landlord/payments")} />
              <AlertBadge count={r.expiring}    color={C.gold}       label="Leases expiring in 30 days"    icon="clock"          onClick={() => navigate("/landlord/leases")} />
              <AlertBadge count={r.expired}     color={C.redLight}   label="Expired leases need action"    icon="file-text"      onClick={() => navigate("/landlord/leases")} />
              <AlertBadge count={r.maintenance} color={C.gold}       label="Open maintenance requests"     icon="tool"           onClick={() => navigate("/landlord/maintenance")} />
              <AlertBadge count={r.complaints}  color={C.purple}     label="Active complaints"             icon="message-square" onClick={() => navigate("/landlord/complaints")} />
              {!r.pending && !r.overdue && !r.expiring && !r.expired && !r.maintenance && !r.complaints && (
                <div style={{ display: "flex", alignItems: "center", gap: ".4rem", padding: ".6rem 0" }}>
                  <div style={{ width: 6, height: 6, borderRadius: "50%", background: C.greenLight }} />
                  <span style={{ fontFamily: F.mono, fontSize: ".6rem", letterSpacing: ".08em", color: C.greenLight, textTransform: "uppercase" }}>All clear</span>
                </div>
              )}
            </Panel>
          </div>

        </div>
      )}
    </div>
  );
}